name: Standalone CLI
on: [push, pull_request]

jobs:
  machineStandalone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Skims scan
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            -w /repo \
            docker.io/fluidattacks/skims:latest \
            skims scan .

      - name: Upload Skims results
        uses: actions/upload-artifact@v3
        with:
          name: skims-results
          path: Fluid-Attacks-Results.csv
